services:
  flask-backend:
    build: .
    container_name: minecraft-panel-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      # Esto permite que si editas el código en tu PC, 
      # el contenedor se actualice sin reconstruir (modo dev)
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - panagaming-network

networks:
  panagaming-network:
    driver: bridge